// Do NOT edit this file!

import static org.junit.jupiter.api.Assertions.*;

import apcsa.githubtrack.*;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import org.junit.jupiter.api.*;

public class ShoppingProjectTest {

  private final ByteArrayOutputStream outContent = new ByteArrayOutputStream();
  private final PrintStream originalOut = System.out;

  @BeforeEach
  public void setUpStreams() {
    System.setOut(new PrintStream(outContent));
  }

  @AfterEach
  public void restoreStreams() {
    System.setOut(originalOut);
    outContent.reset();
  }

  // =========================
  // ShoppingItem Tests
  // =========================

  @Test
  public void testShoppingItemEquals() {
    ShoppingItem a = new ShoppingItem("eggs", 350);
    ShoppingItem b = new ShoppingItem("eggs", 350);
    ShoppingItem c = new ShoppingItem("eggs", 400);

    assertTrue(a.equals(b), "Items with same name and price should be equal");
    assertFalse(a.equals(c), "Items with same name but different price should not be equal");
  }

  @Test
  public void testShoppingItemBuy() {
    ShoppingItem item = new ShoppingItem("milk", 250);
    assertFalse(item.isSold(), "Item should not be sold initially");

    item.buy();
    assertTrue(item.isSold(), "Item should be sold after buy()");

    item.buy(); // should do nothing harmful
    assertTrue(item.isSold(), "Item should remain sold");
  }

  @Test
  public void testCompareToSameItem() {
    ShoppingItem cheap = new ShoppingItem("apple", 100);
    ShoppingItem expensive = new ShoppingItem("apple", 150);

    assertTrue(expensive.compareTo(cheap) > 0);
    assertTrue(cheap.compareTo(expensive) < 0);
    assertEquals(0, cheap.compareTo(new ShoppingItem("apple", 100)));
  }

  @Test
  public void testCompareToDifferentItems() {
    ShoppingItem a = new ShoppingItem("apple", 100);
    ShoppingItem b = new ShoppingItem("banana", 100);

    a.compareTo(b);
    assertTrue(
        outContent.toString().contains("Error: Different items!"),
        "compareTo should print error for different item names");
  }

  @Test
  public void testPriceGetterInDollars() {
    ShoppingItem item = new ShoppingItem("coffee", 525);
    assertEquals(5.25, item.getPrice(), 0.001);
  }

  // =========================
  // ShoppingList Tests
  // =========================

  @Test
  public void testAddToEndAndGetAt() {
    ShoppingList list = new ShoppingList();
    list.addToEnd(new ShoppingItem("a", 100));
    list.addToEnd(new ShoppingItem("b", 200));

    assertEquals(2, list.getSize());
    assertEquals("b", list.getAt(1).getName());
  }

  @Test
  public void testInsertAt() {
    ShoppingList list = new ShoppingList();
    list.addToEnd(new ShoppingItem("a", 100));
    list.addToEnd(new ShoppingItem("c", 300));
    list.insertAt(1, new ShoppingItem("b", 200));

    assertEquals("b", list.getAt(1).getName());
    assertEquals(3, list.getSize());
  }

  @Test
  public void testRemoveAt() {
    ShoppingList list = new ShoppingList();
    list.addToEnd(new ShoppingItem("a", 100));
    list.addToEnd(new ShoppingItem("b", 200));
    list.addToEnd(new ShoppingItem("c", 300));

    list.removeAt(1);

    assertEquals(2, list.getSize());
    assertEquals("c", list.getAt(1).getName());
  }

  @Test
  public void testInvalidIndexHandling() {
    ShoppingList list = new ShoppingList();
    list.getAt(0);
    assertTrue(outContent.toString().contains("Invalid index!"));
  }

  @Test
  public void testCapacityGrowth() {
    ShoppingList list = new ShoppingList();

    for (int i = 0; i < 20; i++) {
      list.addToEnd(new ShoppingItem("item" + i, 100));
    }

    assertEquals(20, list.getSize(), "List should correctly resize when capacity exceeded");
  }

  @Test
  public void testTrimExcessOnEmptyList() {
    ShoppingList list = new ShoppingList();

    // Sanity check: list starts empty
    assertEquals(0, list.getSize(), "New list should start with size 0");

    list.trimExcess();

    // Per spec: capacity must never drop below 8
    assertEquals(8, list.getCapacity(),
            "trimExcess on an empty list should preserve minimum capacity of 8");
  }

  @Test
  public void testGoShoppingAll() {
    ShoppingList list = new ShoppingList();
    list.addToEnd(new ShoppingItem("a", 100));
    list.addToEnd(new ShoppingItem("b", 200));

    list.goShopping();

    assertTrue(list.getAt(0).isSold());
    assertTrue(list.getAt(1).isSold());
  }

  @Test
  public void testGoShoppingWithList() {
    ShoppingList store = new ShoppingList();
    store.addToEnd(new ShoppingItem("a", 100));
    store.addToEnd(new ShoppingItem("b", 200));

    ShoppingList toBuy = new ShoppingList();
    toBuy.addToEnd(new ShoppingItem("b", 200));

    store.goShopping(toBuy);

    assertFalse(store.getAt(0).isSold());
    assertTrue(store.getAt(1).isSold());
  }

  @Test
  public void testIsIdentical() {
    ShoppingList a = new ShoppingList();
    ShoppingList b = new ShoppingList();

    a.addToEnd(new ShoppingItem("x", 100));
    a.addToEnd(new ShoppingItem("y", 200));

    b.addToEnd(new ShoppingItem("y", 200));
    b.addToEnd(new ShoppingItem("x", 100));

    assertTrue(a.isIdentical(b), "Lists with same items in different order should be identical");
  }

  @Test
  public void testTotalPrice() {
    ShoppingList list = new ShoppingList();
    list.addToEnd(new ShoppingItem("a", 100));
    list.addToEnd(new ShoppingItem("b", 250));

    assertEquals(3.50, list.getTotalPrice(), 0.001);
  }

  // =========================
  // ShoppingCart Tests
  // =========================

  @Test
  public void testCartCompletion() {
    ShoppingList list = new ShoppingList();
    list.addToEnd(new ShoppingItem("a", 100));

    ShoppingCart cart = new ShoppingCart("Test User", list);

    assertFalse(cart.isCompleted());

    list.goShopping();
    assertTrue(cart.isCompleted());
  }

  @Test
  public void testReturnCartRules() {
    ShoppingList list = new ShoppingList();
    list.addToEnd(new ShoppingItem("a", 100));

    ShoppingCart cart = new ShoppingCart("User", list);

    cart.returnCart();
    assertEquals(
        0, ShoppingCart.getTotalCartsReturned(), "Cart should not return if not completed");

    list.goShopping();
    cart.returnCart();

    assertEquals(
        1, ShoppingCart.getTotalCartsReturned(), "Completed cart should increment total returned");

    cart.returnCart();
    assertEquals(
        1, ShoppingCart.getTotalCartsReturned(), "Cart should not be returned more than once");
  }
}
